apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluegreen-ingress
  namespace: bluegreen-demo

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: active-service
                port:
                  number: 80

          - path: /preview
            pathType: Prefix
            backend:
              service:
                name: preview-service
                port:
                  number: 80